name: citytube
description: Citytube mobile app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audio_session: ^0.2.2
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  just_audio: ^0.10.3
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
